server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:55433/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  kafka:
    bootstrap-servers: localhost:9096
    consumer:
      group-id: file-worker
      auto-offset-reset: earliest
    listener:
      auto-startup: true

app:
  kafka:
    topic-upload-jobs: upload-jobs

logging:
  level:
    com.zaxxer.hikari: INFO
