name: project1-fileUploader-infra

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: p1-app
    depends_on:
      - postgres
      - kafka
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/appdb
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      APP_TMP_DIR: /tmp/file-uploader
      APP_STORAGE_ENDPOINT: http://minio:9000
      APP_STORAGE_ACCESS_KEY: minio
      APP_STORAGE_SECRET_KEY: minio12345
      APP_STORAGE_BUCKET: uploads
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    image: postgres:16
    container_name: p1-postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=appdb
    ports:
      - "55433:5432"
    volumes:
      - p1_pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: p1-minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio12345
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - p1_minio_data:/data

  kafka:
    image: apache/kafka:latest
    container_name: p1-kafka
    ports:
        - "9092:9092"
        - "19092:19092"
    environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
volumes:
  p1_pg_data:
  p1_minio_data:
  p1_kafka_data:
