server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:55433/appdb
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9096
    consumer:
      group-id: uploader-worker
      auto-offset-reset: earliest
    producer:
      properties:
        spring.json.add.type.headers: false
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  tmp-dir: ./tmp/file-uploader
  kafka:
    topic-upload-jobs: upload-jobs
  outbox:
    batch-size: 50
    enabled: true
    publish-delay-ms: 1000
logging:
  level:
    com.zaxxer.hikari: DEBUG

